baseURL = 'https://blog.raic.tech'
languageCode = 'ja'
title = '雷のブログ'
theme = 'paper'

[params]
twitter = 'raidesuuu'
instagram = 'raisandayoo'
github = 'raidesuuu'
threads = 'raisandayoo'
rss = true

[taxonomies]
  category = 'categories'
  tag = 'tags'

avatar = 'admin@raic.tech'
name = '雷'
bio = '学生です。ゲームが趣味です。'
