baseURL = 'https://blog.raic.tech'
languageCode = "ja-jp"
title = '雷のブログ'
theme = 'paper'

[params]
twitter = 'raidesuuu'
instagram = 'raisandayoo'
github = 'raidesuuu'
threads = 'raisandayoo'
rss = true

avatar = 'admin@raic.tech'
name = '雷'
bio = '学生です。ゲームが趣味です。'
